// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlitestore

import (
	"time"
)

type BLOCKPOINTER struct {
	Name        string
	BlockNumber *int64
	BlockTime   *int64
}

type L1StandardBridgeEthDepositInitiated struct {
	ID                                        int64
	CreatedAt                                 *time.Time
	UpdatedAt                                 *time.Time
	BlockNumber                               int64
	BlockTimestamp                            int64
	TxHash                                    []byte
	FromAddress                               []byte
	ToAddress                                 []byte
	Amount                                    float64
	Event                                     []byte
	MatchingHash                              []byte
	MatchedL2StandardBridgeDepositFinalizedID *int64
}

type L2StandardBridgeDepositFinalized struct {
	ID                                           int64
	CreatedAt                                    *time.Time
	UpdatedAt                                    *time.Time
	BlockNumber                                  int64
	BlockTimestamp                               int64
	TxHash                                       []byte
	FromAddress                                  []byte
	ToAddress                                    []byte
	L1Token                                      []byte
	Amount                                       float64
	Event                                        []byte
	MatchingHash                                 []byte
	MatchedL1StandardBridgeEthDepositInitiatedID *int64
}
