// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package sqlitestore

import (
	"context"
)

const getBlockPointer = `-- name: GetBlockPointer :one
SELECT block_number FROM BLOCK_POINTERS WHERE name = ? LIMIT 1
`

func (q *Queries) GetBlockPointer(ctx context.Context, name string) (*int64, error) {
	row := q.queryRow(ctx, q.getBlockPointerStmt, getBlockPointer, name)
	var block_number *int64
	err := row.Scan(&block_number)
	return block_number, err
}

const insertL1StandardBridgeETHDepositInitiated = `-- name: InsertL1StandardBridgeETHDepositInitiated :exec
INSERT INTO l1_standard_bridge_eth_deposit_initiated (
    block_number,
    block_timestamp,
    tx_hash,
    from_address,
    to_address,
    amount,
    event,
    matching_hash
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type InsertL1StandardBridgeETHDepositInitiatedParams struct {
	BlockNumber    int64
	BlockTimestamp int64
	TxHash         []byte
	FromAddress    []byte
	ToAddress      []byte
	Amount         float64
	Event          []byte
	MatchingHash   []byte
}

func (q *Queries) InsertL1StandardBridgeETHDepositInitiated(ctx context.Context, arg InsertL1StandardBridgeETHDepositInitiatedParams) error {
	_, err := q.exec(ctx, q.insertL1StandardBridgeETHDepositInitiatedStmt, insertL1StandardBridgeETHDepositInitiated,
		arg.BlockNumber,
		arg.BlockTimestamp,
		arg.TxHash,
		arg.FromAddress,
		arg.ToAddress,
		arg.Amount,
		arg.Event,
		arg.MatchingHash,
	)
	return err
}

const updateBlockPointer = `-- name: UpdateBlockPointer :exec
UPDATE BLOCK_POINTERS SET block_number = ? WHERE name = ?
`

type UpdateBlockPointerParams struct {
	BlockNumber *int64
	Name        string
}

func (q *Queries) UpdateBlockPointer(ctx context.Context, arg UpdateBlockPointerParams) error {
	_, err := q.exec(ctx, q.updateBlockPointerStmt, updateBlockPointer, arg.BlockNumber, arg.Name)
	return err
}
